2025-09-19T03:07:11Z info: Deployment: 641d3ecc-2d84-4ed8-a41a-7c505d506dce
2025-09-19T03:07:11Z info: Build: bd22505e-099f-4367-b3ab-f455f70a2119
2025-09-19T03:07:11Z info: Connecting to builder
2025-09-19T03:07:13Z info: Builder connected
2025-09-19T03:07:14Z info: Installing packages
--> uv lock

Resolved 99 packages in 659ms

 v21.2.0, v25.1.0

Removed bidict
click-didyoumean v0.3.1

v11.3.0

in 1ms
Prepared 4 packages in 227ms

Uninstalled 59 packages in 1.15s

Installed 4 packages in 37ms

==
5.3.1
==
==
2025-09-19T03:07:18Z info: Pushing pid1 binary layer...
2025-09-19T03:07:20Z info: Created pid1 binary layer
2025-09-19T03:07:21Z info: Pushing hosting layer...
2025-09-19T03:07:21Z info: Pushing Repl layer...
2025-09-19T03:07:21Z info: Retrieved cached nix layer
2025-09-19T03:07:22Z info: Created hosting layer
2025-09-19T03:07:48Z info: Created Repl layer
2025-09-19T03:07:48Z info: Pushing Repl (cache) layer...
2025-09-19T03:07:48Z info: Created Repl (cache) layer
2025-09-19T03:07:52Z info: Pushed image manifest
2025-09-19T03:07:53Z info: Pushed soci index manifest
2025-09-19T03:07:57Z info: Creating Autoscale service
forwarding local port 5000 to external port 80 (mapped as 1104)
    worker.init_process()
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    self.load_wsgi()
[2025-09-19 03:10:26 +0000] [35] [INFO] Using worker: sync
[2025-09-19 03:10:26 +0000] [35] [INFO] Starting gunicorn 23.0.0
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2025-09-19 03:10:30 +0000] [59] [INFO] Worker exiting (pid: 59)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.load_wsgi()
[2025-09-19 03:10:32 +0000] [60] [INFO] Starting gunicorn 23.0.0
    mod = importlib.import_module(module)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/base.py", line 135, in init_process
    worker.init_process()
  File "/home/runner/workspace/app.py", line 6, in <module>
[2025-09-19 03:10:36 +0000] [72] [ERROR] Shutting down: Master
    self.wsgi = self.app.wsgi()
    self.callable = self.load()
[2025-09-19 03:10:44 +0000] [79] [INFO] Listening at: http://0.0.0.0:5000 (79)
  File "/home/runner/workspace/main.py", line 2, in <module>
    self.load_wsgi()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
                ^^^^^^^^^^^^^^^
crash loop detected
2025-09-19T03:11:35Z error: The deployment is crash looping. This can happen if the run command fails or exits immediately after starting. Check the logs for more information.
